# 错误处理

```js
throw new Error('Ran out of coffee');

class NotEnoughCoffeeError extends Error {
  // ...
}
throw new NotEnoughCoffeeError();

process.on('uncaughtException', err => {
  console.error('There was an uncaught error2', err);
  process.exit(1); // mandatory (as per the Node.js docs)
});

doSomething1()
  .then(doSomething2)
  .then(doSomething3)
  .catch(err => console.error(err));
```

