# 运行时错误

错误场景 如何上报
场景一：自行感知的同步运行时异常：try-catch 后进行错误上报
场景二：没有手动 catch 的运行时异常（包括异步但不包括 promise 异常）：通过 window.onerror进行监听
场景三：自行感知的 promise 异常：promise catch 进行捕获后进行错误上报
场景四：没有手动 catch 的 promise 异常：监听 window 对象的 unhandledrejection 事件
